
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Sep 23 2025 16:16:51 IST (Sep 23 2025 10:46:51 UTC)

// Verification Directory fv/vendingMachine 

module vendingMachine(choco_out, chng_out, clk, reset, two_in, one_in);
  input clk, reset, two_in, one_in;
  output choco_out, chng_out;
  wire clk, reset, two_in, one_in;
  wire choco_out, chng_out;
  wire [2:0] state;
  wire UNCONNECTED, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_13, n_14, n_17, n_18, n_23;
  wire sel;
  OAI22X1 g814__2398(.A0 (two_in), .A1 (n_13), .B0 (one_in), .B1 (n_6),
       .Y (n_18));
  DFFNSRXL sel_reg(.RN (1'b1), .SN (1'b1), .CKN (clk), .D (n_14), .Q
       (sel), .QN (UNCONNECTED));
  SDFFRHQX1 \state_reg[1] (.RN (n_17), .CK (clk), .D (n_23), .SI (n_7),
       .SE (one_in), .Q (state[1]));
  BUFX2 g820(.A (n_14), .Y (choco_out));
  AOI21X1 g818__5107(.A0 (n_23), .A1 (one_in), .B0 (n_10), .Y (n_13));
  NOR3BX1 g819__6260(.AN (two_in), .B (n_9), .C (one_in), .Y (n_11));
  OAI31X1 g821__4319(.A0 (state[0]), .A1 (state[1]), .A2 (n_5), .B0
       (n_4), .Y (n_14));
  CLKINVX1 g822(.A (n_9), .Y (n_10));
  CLKAND2X2 g826__8428(.A (state[2]), .B (n_2), .Y (chng_out));
  NOR2BX1 g823__5526(.AN (n_3), .B (two_in), .Y (n_7));
  NAND3X1 g824__6783(.A (n_1), .B (n_5), .C (two_in), .Y (n_6));
  NAND3X1 g827__3680(.A (state[0]), .B (state[1]), .C (n_5), .Y (n_4));
  NAND2XL g825__1617(.A (state[0]), .B (n_3), .Y (n_9));
  NOR2XL g829__1705(.A (state[0]), .B (state[1]), .Y (n_2));
  NOR2XL g830__5122(.A (state[1]), .B (state[2]), .Y (n_3));
  NOR2XL g831__8246(.A (sel), .B (reset), .Y (n_17));
  DFFRX1 \state_reg[0] (.RN (n_17), .CK (clk), .D (n_18), .Q
       (state[0]), .QN (n_1));
  DFFRX1 \state_reg[2] (.RN (n_17), .CK (clk), .D (n_11), .Q
       (state[2]), .QN (n_5));
  NOR3BX1 g2(.AN (state[1]), .B (state[2]), .C (state[0]), .Y (n_23));
endmodule

